### ISSUE TITLE
Can't send numeric values through the Zabbix output

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-output-zabbix#1]
from https://logstash.jira.com/browse/LOGSTASH-2223

In Logstash 1.4.1 and Zabbix 2.2, exceptions are thrown when I try to send a number to Zabbix. For example, I set the send_field value to "some-metric.count".

Logstash throws an error:
{code}
{
:timestamp=>"2014-05-24T04:59:12.348000-0500", 
:message=>"Error during receiving message for sending", 
:event=>#<LogStash::Event:0x3f6600b8 ...>, 
:exception=>#<NoMethodError: undefined method `empty?' for 17:Fixnum>, 
:backtrace=>[
    "file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/shellwords.rb:75:in `shellescape'", 
    "/opt/logstash/lib/logstash/outputs/zabbix.rb:115:in`receive'", 
    "org/jruby/RubyArray.java:1613:in `each'", 
    "org/jruby/RubyEnumerable.java:977:in`each_with_index'", 
    "/opt/logstash/lib/logstash/outputs/zabbix.rb:112:in `receive'", 
    "/opt/logstash/lib/logstash/outputs/base.rb:86:in`handle'", 
    "(eval):456:in `initialize'", 
    "org/jruby/RubyProc.java:271:in`call'", 
    "/opt/logstash/lib/logstash/pipeline.rb:266:in `output'", 
    "/opt/logstash/lib/logstash/pipeline.rb:225:in`outputworker'", 
    "/opt/logstash/lib/logstash/pipeline.rb:152:in `start_outputs'"
], 
:level=>:warn
}
{code}

Am I doing something wrong, or is sending numbers to Zabbix just not supported?

**Comment by untergeek** [comment]
Zabbix receives numeric strings and converts internally

**Comment by untergeek** [comment]
This will be addressed by https://github.com/logstash-plugins/logstash-output-zabbix/pull/2

**Comment by untergeek** [comment]
This issue should be resolved.  Re-open if necessary.
