### ISSUE TITLE
Logstash crashes trying to send cyrillic message

### ISSUE THREAD

**Issue by akosyrev** [logstash-plugins/logstash-output-zabbix#13]
when logstash-output-zabbix got something like that "Привет" to send it fails with:

Encoding::CompatibilityError: incompatible encodings: ASCII-8BIT and UTF-8
            join at org/jruby/RubyArray.java:1892
            join at org/jruby/RubyArray.java:1898
            dump at /opt/logstash/vendor/bundle/jruby/1.9/gems/zabbix_protocol-0.1.4/lib/zabbix_protocol.rb:22
        tcp_send at /opt/logstash/vendor/local_gems/474b106e/logstash-output-zabbix-2.0.0/lib/logstash/outputs/zabbix.rb:202
            open at org/jruby/RubyIO.java:1183
        tcp_send at /opt/logstash/vendor/local_gems/474b106e/logstash-output-zabbix-2.0.0/lib/logstash/outputs/zabbix.rb:200
  send_to_zabbix at /opt/logstash/vendor/local_gems/474b106e/logstash-output-zabbix-2.0.0/lib/logstash/outputs/zabbix.rb:223
         timeout at org/jruby/ext/timeout/Timeout.java:115
  send_to_zabbix at /opt/logstash/vendor/local_gems/474b106e/logstash-output-zabbix-2.0.0/lib/logstash/outputs/zabbix.rb:222
         receive at /opt/logstash/vendor/local_gems/474b106e/logstash-output-zabbix-2.0.0/lib/logstash/outputs/zabbix.rb:239
          handle at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80
     output_func at (eval):77
    outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:252
   start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:169

**Comment by akosyrev** [comment]
Ok, I did some research for this error.

It raises only if "value" length >18chars (consequently, length of full message is more than 127) and there is at least one russian letter:
1. value "qqwweerrttyyuuiioщ" has 17 latin and 1 russian letters, so it wil raise that error
2. value "ййццууккееннггшшщщ" has 18 russian letters and raise error too
3. value "ййццууккееннггшшщ" has 17 russian letters and it will be passed to zabbix w/o any error

**Comment by akosyrev** [comment]
Fixed in zabbix_protocol.rb:
[payload.length].pack('Q')**.to_s.force_encoding("UTF-8")**
I don't have any idea why, but it works now

**Comment by untergeek** [comment]
Hmmm. I don't own the [zabbix_protocol](https://github.com/winebarrel/zabbix_protocol) project.  Would you mind opening an issue there with these findings?  I can't patch it as part of this project.

**Comment by akosyrev** [comment]
ok, thank you

https://github.com/winebarrel/zabbix_protocol/issues/2
