### ISSUE TITLE
How to convert to latest zabbix output?

### ISSUE THREAD

**Issue by ScottChapman** [logstash-plugins/logstash-output-zabbix#3]
Could you include some example that shows how to send data for multiple items for a single host?
Having difficulty understanding how to construct the data to make this work properly.

**Comment by untergeek** [comment]
Currently, the plugin only sends one value per event. If there comes a need to send multiple values for a single event, a refactoring will have to take place.

**Comment by ScottChapman** [comment]
Yea, definately need that. We were sending some JSON in a message and it included several items/value pairs.

**Comment by untergeek** [comment]
You should be able to upgrade to the latest version of the plugin now.

```
bin/plugin update logstash-output-zabbix
```

If you installed Logstash 1.5.1, it's not included, so you have to install it:

```
bin/plugin install logstash-output-zabbix
```

The main documentation hasn't been updated yet, but this is extracted from the code:

```
  # Use the `multi_value` directive to send multiple key/value pairs.
  # This can be thought of as an array, like:
  #
  # `[ zabbix_key1, zabbix_value1, zabbix_key2, zabbix_value2, ... zabbix_keyN, zabbix_valueN ]`
  #
  # ...where `zabbix_key1` is an instance of `zabbix_key`, and `zabbix_value1`
  # is an instance of `zabbix_value`.  If the field referenced by any
  # `zabbix_key` or `zabbix_value` does not exist, that entry will be ignored.
  #
  # This directive cannot be used in conjunction with the single-value directives
  # `zabbix_key` and `zabbix_value`.
  config :multi_value, :validate => :array
```

This means that you can use:

```
output {
  zabbix {
    zabbix_server_host => '127.0.0.1'
    zabbix_server_port => 10051
    zabbix_host => 'hostfield'
    multi_value => [ 'keyfield1', 'valuefield1', 'keyfield2', 'valuefield2']
  }
}
```

**Comment by untergeek** [comment]
Closing as this has not been updated in several months.
